### ISSUE TITLE
Can't get posts to show

### ISSUE THREAD

**Issue by wmhunter96** [panr/hugo-theme-hello-friend#91] opened 2019-08-30 19:32 UTC
Hey, I'm new to hugo and love your theme but i've tried to follow examples and can't seem to get my posts to show

https://github.com/wmhunter96/hunterrodriguez

**Comment by thomasjsn** [comment] 2019-09-04 20:29
The minimum Hugo version for this theme is 0.57, is your Hugo version up to date?

**Comment by gkaramanis** [comment] 2019-10-06 13:12
Same here. I can't see the posts on the `home` page, they show fine on `archive`.
I have Hugo 0.58.3 both on my machine and on Netlify. 

https://karamanis.netlify.com
https://github.com/gkaramanis/karaman.is

Love the theme, by the way!

**Comment by panr** [comment] 2019-10-06 21:28
@gkaramanis the theme's looking for `content/post` dir by default (you can change it in `config.toml`). I see that you have many other catalogs in `content` and none of those match default settings.

**Comment by gkaramanis** [comment] 2019-10-07 04:27
I was trying different directories, must have missed it when I pushed to GitHub, sorry about that. 

I've changed it back to `posts` but I can't see any posts. And it seems that they stopped showing on `archives`, too 🤔

**Comment by panr** [comment] 2019-10-07 16:07
@gkaramanis OK, I cloned your repo (do you know it weights ~3GB? 😱) and based on your folder structure inside content, I changed `contentTypeName = "posts"` to `post` (it's because you manualny set type of each post, so you can name this folder whatever you want until you have this `type: post` inside your front matter. I didn't get that at first glance.).

Also you have your own `index.html` layout, so all your posts (files with `type: post`) are on route `/posts` (name of your folder).

I hope this helps you ;-)

**Comment by gkaramanis** [comment] 2019-10-07 16:21
Yes, I knew about the size, that’s the result of having a photography site for 7+ years :) The structure was probably a little messy since it was a migration from Squarespace.

Big thanks for the help, I think I understood what the problem is! 🙏

**Comment by panr** [comment] 2019-10-07 16:24
Fingers crossed then 🤞

**Comment by gkaramanis** [comment] 2019-10-07 19:27
Just to confirm that `index.html`  inside the `layouts` folder (from the previous) was the culprit. Thanks again!

**Comment by panr** [comment] 2019-10-07 19:37
Glad to here it! I'm closing the issue 😎

**Closed by panr** 2019-10-07 19:37 UTC
